FROM diygod/rsshub@sha256:44abdc89a6da34574efb8c52ce54ce51a822e347e5432270bf6d7ad759c7d83f
COPY --chown=root:root anthropic-research-Cc3-u2wm.mjs /app/dist/anthropic-research-Cc3-u2wm.mjs
COPY --chown=root:root reuters-common-H2jR6R7j.mjs /app/dist/reuters-common-H2jR6R7j.mjs
